[project]
name = "first-agent"
version = "0.1.0"
description = "Here is my first AI Agent "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.0.17",
    "python-dotenv>=1.1.0",
]
